### ISSUE TITLE
Issue right click contextual menu doesn't fit in browser window

### ISSUE THREAD

**Issue by rafaponieman** [pixel-cookers/redmine-theme#10]
If a ticket is way up the list, the sub-sub-context menu doesn't fit in the browser window (screenshot: http://storage2.static.itmages.com/i/12/1025/h_1351151168_9220655_1f1acb05be.png).

Using redmine: Redmine 1.2.1.stable.7706 (PostgreSQL)
RedmineThemePixelCokers: latest github version

**Comment by lmeyer** [comment]
Hello,

I think this is a redmine core problem. Can you confirm that the problem occurs only with the theme activated ?
If not, you can report the bug at http://www.redmine.org.
