### ISSUE TITLE
Formatting of the "code" tag is broken

### ISSUE THREAD

**Issue by null12** [pixel-cookers/redmine-theme#19]
Multiline content within the &lt;code&gt; tag like

<pre>
&lt;code&gt;
line 1
line 2
&lt;/code&gt;
</pre>

is displayed as single line

<pre>line 1 line 2</pre>

because of

<pre>
code {
....
      white-space: nowrap;
    }
</pre>

in the CSS.

**Comment by lmeyer** [comment]
Forgot to push...

The fix is in current master.
