### ISSUE TITLE
Error editing issues

### ISSUE THREAD

**Issue by jlmera** [pixel-cookers/redmine-theme#21]
When editing an issues and by clicking accept an error is generated (in the picture) using firefox 22

![error](https://f.cloud.github.com/assets/1661630/750988/e3d83bb0-e4e3-11e2-9f89-10ea8b26fda5.jpg)

Seeking found the charge:

$('.controller-issues.action-show #issue-form input[type="submit"], .controller-timelog .edit_time_entry input[type="submit"], .controller-timelog .new_time_entry input[type="submit"]').on('click', function(){
                window.onbeforeunload = function (e) {
                    var e = e || window.event;
                    if (e) {
                        e.returnValue = null;
                    }
                    return null;
                };
            });

**Comment by Tide** [comment]
I am getting this error as well.

**Comment by jaugustin** [comment]
@jlmera @Tide  could you test the last master version, and say if this fix your issue.

**Comment by Tide** [comment]
That seems to have fixed it.  Thanks for the good work and great theme!
