### ISSUE TITLE
Redmine 1.3.0 compatibility

### ISSUE THREAD

**Issue by syntacticvexation** [pixel-cookers/redmine-theme#4]
I really like this theme, I think it's great.  Since upgrading to Redmine 1.3.0 however I've noticed a few formatting oddities.  I've linked to screenshots.

[Repository formatting](https://docs.google.com/open?id=0B4xYGxUNQi1DODI4ZGJiZjYtZWQyYy00MjM4LWI5YjgtYWRkZWQzYWIyMWJk)

[Wiki formatting](https://docs.google.com/open?id=0B4xYGxUNQi1DM2Q5ZTM1YjgtZDJmOC00ZGQ5LWI1ZDUtNjQwNGUyNzkzYWQ2)

The Wiki formatting problem seems to happen when a section ends with a ordered list.

Thanks heaps.

**Comment by camilonova** [comment]
I also add this one:

http://cl.ly/3c42462G1Z161H2P2R0T

Great job on this :D

**Comment by lmeyer** [comment]
Wiki bug has been fixed by 6d968bb7d764eb022a28c6fe25bd2629ccd083b4

**Comment by lmeyer** [comment]
Contextual menu has been fixed by 6d968bb7d764eb022a28c6fe25bd2629ccd083b4

**Comment by lmeyer** [comment]
The repository formatting seems to be ok now

http://awesomescreenshot.com/0dd89qi59

**Comment by syntacticvexation** [comment]
Looks great, thanks heaps. :)
