### ISSUE TITLE
bullet_white.png/square_black.png not found

### ISSUE THREAD

**Issue by thijssimonis** [pixel-cookers/redmine-theme#5]
Patch:

<code>--- factory.application.css     2012-02-22 18:11:35.000000000 +0400
+++ application.css     2012-02-22 18:24:15.000000000 +0400
@@ -406,10 +406,10 @@
        padding:4px 0 4px 20px;
 }
 ul li li{
-       background-image: url(../images/icons/bullet_white.png);
-       background-image: url(../images/bullet_white.png);
  }
  ul li li li{
-       background-image: url(../images/icons/bullet_white.png);
-       background-image: url(../images/square_black.png);
  }
  ul.projects.root li.root{
        background: none;

</code>

**Comment by baracoder** [comment]
May be it is better fix by moving the icons to icon folder?

**Comment by lmeyer** [comment]
List bullets are not really icons. They are here for cosmetic matters.
Defaut list image moved to "/images/" folder.
