### ISSUE TITLE
Compatibility with redmine 2.0.x

### ISSUE THREAD

**Issue by rasca** [pixel-cookers/redmine-theme#7]
As is, the theme works but several things break. It would be nice to support both 1.4.x and 2.0.x.

**Comment by lmeyer** [comment]
Hello rasca, 

Can you tell me where the theme breaks in new versions.

I am currently upgrading the theme for 1.4.x. I've done some fixes but maybe I miss something.

**Comment by rasca** [comment]
I haven't had much time to play with it and I didn't test all the modules but what comes up really quick is the Administration menu

![menu image](http://i49.tinypic.com/2i1l2mb.png)

```
<ul>
     <ul><li><a href="/admin/projects" class="projects selected">Projects</a></li>
         <li><a href="/users" class="users">Users</a></li>
```

If I find more things I'll report back. Thanks!

**Comment by lmeyer** [comment]
The selected item in sidebar has been fixed in a previous commit (included in current master).

I close this issue, please open another for each bug you find.

Cheers
