### ISSUE TITLE
a small glitch

### ISSUE THREAD

**Issue by gituser** [pixel-cookers/redmine-theme#8]
many thanks for your hard work!

loving this theme.. 

however could you plz fix this:

http://i.imgur.com/5iEMd.jpg

happens when I hit an update button in the issue inside (checked classic theme it's not happening there), also icon's replacing text seems to be weird instead of replacing text they are showing up on the text.. (right panel should be on otherwise it's almost unnoticeable).

also I'd like to know how can I resize left panel? Let's say I want to make it little bit smaller and also spacing between main content and left panel would be nice to get it bit smaller.

Thanks again

**Comment by lmeyer** [comment]
it was the no-wrap in #attachments_fields span which caused the problem.
I fixed it.

If you want to resize the left panel you can do it with the #content width in application.less line 161 (don't forget to play with the sidebar width too).

#content and #sidebar are near line 380 in css file.

**Comment by gituser** [comment]
thanks a lot! will check it after hols.

**Comment by gituser** [comment]
hi

i've finally had some time to update to redmine 2.2.4 and also updated theme and tried what you've suggested.

unfortunately, it was NOT easy:
1. you're using bg-color.png file to render the left panel (so it has fixed size instead of variable) and to modify you need to alter image which is not very convinient, any chance you can make just a bg-color fill on the left panel, just like on the right?
2. also i had to edit all margins and width parameters of the left panel and ul style block manually speicifying width in px 
3. for some reason h1 goes after quick search (it's a redmine thing?), so it's square instead of rectangle, i had to change position:relative to position:absolute to get it before quick search box
4. what is for application.less ? modifying it didnt give me any changes, but  modifying application.css worked

sorry for stupid question and big thanks for your work!

**Comment by jaugustin** [comment]
@gituser `application.less` is used to compile `application.css` with a less compiler http://lesscss.org/

**Comment by gituser** [comment]
thanks for the answer!

i have another issue here appearing on pages where there is no sidebar.

it seems to cut up space on #content if earlier sidebar was disabled on such pages.

http://i.imgur.com/3gVRCSw.png

**Comment by lmeyer** [comment]
@gituser, 
1. I'm using a bg image because there is a texture in it. You don't really need to resize the image, you can play with the background-position (if the sidebar is smaller).
2. The HTML (and order of elements in DOM) is redmine specific, the theme is only css
3. @jaugustin answered
4. How did you achieve having no sidebar. If i know, maybe i will be able to reproduce it and maybe find a solution for you.

**Comment by gituser** [comment]
1. OK, thanks for the tip!
2. Yeah, guessed so.
3. OK
4. very simple, just go to any page and click to hide the sidebar, than go to the files page or any other without sidebar. I've just checked after clearing cookies it's happening

Also I noticed if window is resized sidebar-button is not placed accurately

http://i.imgur.com/QthRmpt.png

If I resize some more elements are messed up a bit (maybe width should be fixed, i.e. 900px at minimum?)

http://i.imgur.com/Uyr4TFV.png

**Comment by luisr9** [comment]
Hi lmeyer,

thank you, the theme is wonderfull.

I have a trouble :(

![captura3](https://f.cloud.github.com/assets/5084979/852569/1d1eb70a-f4b6-11e2-93f3-feb26dd133a3.PNG)

the menu (see left) no is complete, and the page no have scroll bar.

Temporally  I am changing the zoom in the browser, but I want fix.

help me please :(

sorry for my english.

thank you in advance.
