### ISSUE TITLE
List overlaps H2

### ISSUE THREAD

**Issue by thijssimonis** [pixel-cookers/redmine-theme#9]
The list overlaps the header h2.
See: http://i.imgur.com/HlVfW.png

I fixed it with the following patch.

<pre>--- application.css     2012-07-30 11:40:49.000000000 +0200
+++ application.css     2012-07-30 11:40:04.000000000 +0200
@@ -472,7 +472,7 @@
   border-top: 1px solid #e3ecfc;
   color: #000000;
   font-size: 16px;
-  margin: 6px -10px 10px;
+  margin: -6px -10px 10px;
   padding: 10px 20px;
 }
 h3,</pre>

**Comment by lmeyer** [comment]
Already fixed in a previous commit with the same patch.

Care, now the source file is add .less file.
